Repository afmireski/garchop-api, pull requests merged in 2024-04, with the labels that each got.

#18 #16 - Implementar rota de Login na plataforma
  CHANGELOG.md
  cmd/main.go
  docs/structure.md
  go.mod
  go.sum
  internal/adapters/bcrypt-hash-helper.go
  internal/adapters/supabase-authenticator.go
  internal/adapters/supabase-users-repository.go
  internal/ports/authenticator-port.go
  internal/ports/hash-helper-port.go
  internal/ports/user-repository-port.go
  internal/services/auth-service.go
  internal/services/users-service.go
  internal/types/input-types.go
  internal/types/output-types.go
  internal/validators/basic-validators.go
  internal/web/controllers/auth-controller.go
  internal/web/controllers/users-controller.go
  internal/web/routers/auth-router.go
Labels: enhancement

#22 #4 - Implementar rota que permita a atualização das informações de um usuário
  CHANGELOG.md
  internal/adapters/supabase-users-repository.go
  internal/models/users-model.go
  internal/ports/user-repository-port.go
  internal/services/users-service.go
  internal/types/input-types.go
  internal/types/output-types.go
  internal/web/controllers/users-controller.go
  internal/web/routers/user-router.go
Labels: enhancement, Backend

#23 #9 - Implementar rota que permita o cadastro de um novo pokémon
  .env.example
  .github/pull_request_template.md
  CHANGELOG.md
  cmd/main.go
  go.mod
  go.sum
  internal/adapters/supabase-pokemon-types-repository.go
  internal/adapters/supabase-pokemon.repository.go
  internal/entities/pokemon.go
  internal/ports/pokemon-repository-port.go
  internal/ports/pokemon-types-port.go
  internal/services/pokemon-service.go
  internal/types/pokemon-types.go
  internal/validators/basic-validators.go
  internal/web/controllers/pokemon-controller.go
  internal/web/routers/pokemon-router.go
Labels: enhancement

#24 #20 - Implementar rota que exiba as informações detalhadas de um Pokémon
  CHANGELOG.md
  cmd/main.go
  internal/adapters/supabase-pokemon-repository.go
  internal/adapters/supabase-pokemon-types-repository.go
  internal/adapters/supabase-users-repository.go
  internal/entities/pokemon-type.go
  internal/entities/pokemon.go
  internal/entities/tier.go
  internal/entities/users.go
  internal/models/pokemon-model.go
  internal/models/pokemon-types-model.go
  internal/models/price-model.go
  internal/models/stock-model.go
  internal/models/tiers-model.go
  internal/models/type-model.go
  internal/models/users-model.go
  internal/ports/pokemon-repository-port.go
  internal/services/pokemon-service.go
  internal/services/users-service.go
  internal/web/controllers/pokemon-controller.go
  internal/web/routers/pokemon-router.go
Labels: enhancement, Backend

#25 #12 - Implementar rota que permita listar todos os pokémons que estão a venda
  CHANGELOG.md
  internal/adapters/supabase-pokemon-repository.go
  internal/entities/pokemon.go
  internal/ports/pokemon-repository-port.go
  internal/services/pokemon-service.go
  internal/web/controllers/pokemon-controller.go
  internal/web/routers/pokemon-router.go
Labels: enhancement, Backend

#26 #11 - Implementar rota que permita listar todos os pokémons que estão a venda
  .env.example
  CHANGELOG.md
  cmd/main.go
  internal/adapters/supabase-pokemon-repository.go
  internal/ports/pokemon-repository-port.go
  internal/services/pokemon-service.go
  internal/web/controllers/pokemon-controller.go
  internal/web/routers/pokemon-router.go
Labels: enhancement, Backend

#28 #10 - Implementar rota de cadastro de conta administrativa
  CHANGELOG.md
  internal/adapters/supabase-users-repository.go
  internal/ports/user-repository-port.go
  internal/services/users-service.go
  internal/types/input-types.go
  internal/validators/basic-validators.go
  internal/web/controllers/users-controller.go
  internal/web/routers/user-router.go
Labels: enhancement, Backend

#29 #27 - Implementar listagem dos Tiers existentes
  CHANGELOG.md
  cmd/main.go
  internal/adapters/supabase-pokemon-repository.go
  internal/adapters/supabase-tiers-repository-port.go
  internal/entities/tier.go
  internal/ports/tiers-repository-port.go
  internal/services/tiers-service.go
  internal/web/controllers/tiers-controller.go
  internal/web/routers/tiers-router.go
Labels: enhancement, Backend

#31 #13 - Implementar rota que permita a listagem de usuários administrativos
  CHANGELOG.md
  internal/adapters/supabase-users-repository.go
  internal/entities/users.go
  internal/ports/user-repository-port.go
  internal/services/users-service.go
  internal/web/controllers/users-controller.go
  internal/web/routers/user-router.go
Labels: Backend

#32 #21 - Implementar rota que permita a um administrador editar os detalhes de um Pokémon
  CHANGELOG.md
  internal/adapters/supabase-pokemon-repository.go
  internal/entities/pokemon.go
  internal/services/pokemon-service.go
  internal/types/input-types.go
  internal/types/pokemon-types.go
  internal/web/controllers/pokemon-controller.go
  internal/web/routers/pokemon-router.go
Labels: enhancement

#35 #34 bug usuarios excluidos estao sendo listados nas buscas de usuario
  CHANGELOG.md
  internal/adapters/supabase-tiers-repository.go
  internal/adapters/supabase-users-repository.go
  internal/ports/user-repository-port.go
  internal/services/users-service.go
Labels: 🐞 bug, Backend
